import Link from "next/link";

export default function Page() {
  return (
    <>
      <h1>ユーザ</h1>
      <div>ユーザ設定画面</div>
      <div>
        <div>
          <div>アイコン</div>
          <div>ユーザ情報</div>
        </div>
        <div>
          <div>
            <h3>SNS連携状況</h3>
            <div>
              <span>SNS1</span>
              <span>連携状況</span>
              <span>連携ボタン</span>
            </div>
          </div>
          <div>
            <h3>リーダー機能</h3>
            <div>
              <div>
                <div>閲覧履歴</div>
                <div>件数</div>
              </div>
              <div>
                <div>お気に入り一覧</div>
                <div>件数</div>
              </div>
              <div>
                <div>メモ一覧</div>
                <div>件数</div>
              </div>
              <div>
                <div>感想一覧</div>
                <div>件数</div>
              </div>
            </div>
          </div>
          <div>
            <h3>クリエイター機能</h3>
            <div>
              <div>
                <div>自分の作品</div>
                <div>件数</div>
              </div>
              <div>
                <div>パーツ登録</div>
                <div>件数</div>
              </div>
              <div>
                <div>グループ編集</div>
                <div>件数</div>
              </div>
              <div>
                <div>パレット追加</div>
                <div>件数</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
